#!/bin/bash
#
# JWT Key Rotation Script
#
# This script rotates JWT signing keys by generating a new key and updating
# the JWT_KEY_CONFIG environment variable. The old key is retained for a
# grace period to allow existing tokens to continue working.
#
# Usage:
#   ./scripts/rotate-jwt-keys.sh [OPTIONS]
#
# Options:
#   --emergency      Perform emergency rotation (immediate old key expiration)
#   --revoke-all     Revoke all previous keys (use with caution!)
#   --grace-days N   Override grace period (default: 90 days)
#   --dry-run        Show what would be done without making changes
#   --help           Show this help message
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
GRACE_PERIOD_DAYS=90
DRY_RUN=false
EMERGENCY=false
REVOKE_ALL=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --emergency)
      EMERGENCY=true
      shift
      ;;
    --revoke-all)
      REVOKE_ALL=true
      shift
      ;;
    --grace-days)
      GRACE_PERIOD_DAYS="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --help)
      head -n 20 "$0" | tail -n +2 | sed 's/^# \?//'
      exit 0
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      exit 1
      ;;
  esac
done

echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║           LibyaChain JWT Key Rotation Tool                     ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if Node.js is available
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    exit 1
fi

# Check if JWT_KEY_CONFIG or JWT_SECRET exists
if [ -z "$JWT_KEY_CONFIG" ] && [ -z "$JWT_SECRET" ]; then
    echo -e "${RED}Error: Neither JWT_KEY_CONFIG nor JWT_SECRET is set${NC}"
    echo "Please set one of these environment variables first."
    exit 1
fi

# Display current configuration
echo -e "${YELLOW}Current Configuration:${NC}"
if [ -n "$JWT_KEY_CONFIG" ]; then
    echo "  Mode: Key Rotation Enabled"

    # Parse current config to show key count
    KEY_COUNT=$(echo "$JWT_KEY_CONFIG" | node -e "
      const config = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
      console.log(config.keys.length);
    ")

    echo "  Active Keys: $KEY_COUNT"
else
    echo "  Mode: Legacy (single JWT_SECRET)"
    echo -e "  ${YELLOW}⚠ This will be the first rotation - a new config will be created${NC}"
fi

echo ""
echo -e "${YELLOW}Rotation Settings:${NC}"
echo "  Grace Period: $GRACE_PERIOD_DAYS days"
echo "  Emergency Mode: $([ "$EMERGENCY" = true ] && echo 'YES ⚠' || echo 'No')"
echo "  Revoke All: $([ "$REVOKE_ALL" = true ] && echo 'YES ⚠⚠⚠' || echo 'No')"
echo "  Dry Run: $([ "$DRY_RUN" = true ] && echo 'YES' || echo 'No')"
echo ""

# Warning for dangerous operations
if [ "$EMERGENCY" = true ] || [ "$REVOKE_ALL" = true ]; then
    echo -e "${RED}⚠  WARNING: This is a destructive operation!${NC}"
    [ "$EMERGENCY" = true ] && echo "   • Emergency mode will immediately invalidate the current key"
    [ "$REVOKE_ALL" = true ] && echo "   • All previous keys will be revoked (all tokens will be invalid)"
    echo ""

    if [ "$DRY_RUN" = false ]; then
        read -p "Are you sure you want to proceed? (type 'yes' to confirm): " CONFIRM
        if [ "$CONFIRM" != "yes" ]; then
            echo "Aborted."
            exit 0
        fi
    fi
fi

# Generate new key and perform rotation
echo -e "${BLUE}Generating new JWT key...${NC}"

NEW_CONFIG=$(node -e "
const crypto = require('crypto');

// Generate new key
function generateKey() {
  return crypto.randomBytes(64).toString('base64').replace(/\\+/g, '-').replace(/\\//g, '_').replace(/=/g, '');
}

const newKey = {
  kid: \`key-\${Date.now()}-\${crypto.randomBytes(4).toString('hex')}\`,
  secret: generateKey(),
  createdAt: new Date().toISOString(),
  isCurrent: true,
  description: 'Generated by rotate-jwt-keys.sh on ' + new Date().toISOString()
};

// Load existing config or create new one
let config;
const configJson = process.env.JWT_KEY_CONFIG;
const legacySecret = process.env.JWT_SECRET;

if (configJson) {
  config = JSON.parse(configJson);
} else if (legacySecret) {
  // First rotation - convert from legacy
  config = {
    keys: [{
      kid: 'legacy',
      secret: legacySecret,
      createdAt: new Date().toISOString(),
      isCurrent: true,
      description: 'Legacy key from JWT_SECRET'
    }],
    gracePeriodDays: $GRACE_PERIOD_DAYS,
    rotationIntervalDays: 90
  };
} else {
  throw new Error('No JWT configuration found');
}

// Perform rotation based on mode
if ($REVOKE_ALL) {
  // Nuclear option - revoke all previous keys
  config.keys = [newKey];
} else if ($EMERGENCY) {
  // Emergency rotation - expire current key immediately
  config.keys = config.keys.map(key => {
    if (key.isCurrent) {
      return { ...key, isCurrent: false, expiresAt: new Date().toISOString() };
    }
    return key;
  });
  config.keys.push(newKey);
} else {
  // Normal rotation - grace period for old keys
  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + $GRACE_PERIOD_DAYS);

  config.keys = config.keys.map(key => {
    if (key.isCurrent) {
      return { ...key, isCurrent: false, expiresAt: expiresAt.toISOString() };
    }
    return key;
  });
  config.keys.push(newKey);

  // Clean up expired keys
  const now = new Date();
  config.keys = config.keys.filter(key => {
    if (!key.expiresAt) return true;
    return new Date(key.expiresAt) > now;
  });
}

console.log(JSON.stringify(config, null, 2));
")

if [ $? -ne 0 ]; then
    echo -e "${RED}Error generating new configuration${NC}"
    exit 1
fi

echo -e "${GREEN}✓ New key generated successfully${NC}"
echo ""

# Show summary
echo -e "${YELLOW}New Configuration Summary:${NC}"
echo "$NEW_CONFIG" | node -e "
const config = JSON.parse(require('fs').readFileSync(0, 'utf-8'));
const currentKey = config.keys.find(k => k.isCurrent);
const validKeys = config.keys.filter(k => !k.expiresAt || new Date(k.expiresAt) > new Date());

console.log('  Total Keys:', config.keys.length);
console.log('  Valid Keys:', validKeys.length);
console.log('  Current Key ID:', currentKey.kid);
console.log('  Grace Period:', config.gracePeriodDays, 'days');
"

echo ""

if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}DRY RUN - Configuration not applied${NC}"
    echo ""
    echo "New JWT_KEY_CONFIG would be:"
    echo "$NEW_CONFIG"
    exit 0
fi

# Apply the new configuration
echo -e "${BLUE}Applying new configuration...${NC}"
echo ""
echo -e "${YELLOW}To apply this configuration, set the JWT_KEY_CONFIG environment variable:${NC}"
echo ""
echo "export JWT_KEY_CONFIG='$(echo "$NEW_CONFIG" | tr -d '\n' | tr -s ' ')'"
echo ""
echo -e "${YELLOW}Or save to a file and source it:${NC}"
echo ""
echo "cat > /etc/libyachain/jwt-config.json <<'EOF'"
echo "$NEW_CONFIG"
echo "EOF"
echo ""
echo "export JWT_KEY_CONFIG=\$(cat /etc/libyachain/jwt-config.json)"
echo ""

# Optionally write to .env.jwt-rotation (not committed to git)
ENV_FILE=".env.jwt-rotation"
echo "$NEW_CONFIG" > "$ENV_FILE"
echo -e "${GREEN}✓ Configuration saved to $ENV_FILE${NC}"
echo ""

echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                  Rotation Complete                             ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Update JWT_KEY_CONFIG in your environment"
echo "  2. Restart all services that use JWT authentication"
echo "  3. Monitor logs for any authentication issues"
echo "  4. Old tokens will remain valid for $GRACE_PERIOD_DAYS days"
echo ""
echo -e "${BLUE}Monitoring:${NC}"
echo "  • Check token verification metrics"
echo "  • Monitor for failed authentication attempts"
echo "  • Verify new tokens include 'kid' header"
echo ""

if [ "$EMERGENCY" = true ]; then
    echo -e "${RED}⚠  EMERGENCY ROTATION COMPLETE${NC}"
    echo "  All tokens signed with the old key are now invalid!"
    echo ""
fi

if [ "$REVOKE_ALL" = true ]; then
    echo -e "${RED}⚠⚠⚠  ALL PREVIOUS KEYS REVOKED${NC}"
    echo "  All existing tokens are now invalid!"
    echo "  Users will need to re-authenticate."
    echo ""
fi

exit 0
