name: Release (Linux)

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write  # needed to create a GitHub Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Build (Linux amd64)
        env:
          CGO_ENABLED: "1"
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential
          go build -v -o libyachaind ./cmd/libyachaind

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: libyachaind
          generate_release_notes: true
